import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import runReadmeGenerator from '@bitnami/readme-generator-for-helm';

// Constraints add rules that Bitnami's parameter metadata cannot express.
function mergeSchema(generated, constraints) {
  for (const [key, value] of Object.entries(constraints)) {
    if (value !== null && typeof value === 'object' && !Array.isArray(value)) {
      generated[key] = mergeSchema(generated[key] ?? {}, value);
    } else {
      generated[key] = value;
    }
  }
  return generated;
}

const root = resolve(import.meta.dirname, '../..');
for (const name of ['minikube-cluster-autoscaler-addon', 'autoscaling-demo']) {
  const chart = resolve(root, 'charts', name);
  const schema = resolve(chart, 'values.schema.json');
  const readme = resolve(chart, 'README.md');
  runReadmeGenerator({
    values: resolve(chart, 'values.yaml'),
    readme,
    schema,
  });
  const generated = JSON.parse(readFileSync(schema, 'utf8'));
  const constraints = JSON.parse(readFileSync(resolve(chart, 'values.schema.constraints.json'), 'utf8'));
  const result = mergeSchema(generated, constraints);
  result.$schema = 'http://json-schema.org/draft-07/schema#';
  result.$comment = 'Generated by make chart-docs from values.yaml and values.schema.constraints.json.';
  writeFileSync(schema, `${JSON.stringify(result, null, 2)}\n`);
  writeFileSync(readme, `${readFileSync(readme, 'utf8').trimEnd()}\n`);
}
